export const BannerTypes = [
	"Standard",
	"FactionWarning",
	"FactionLevelUp",
	"FactionLevelDown",
	"FactionDiscovered",
	"IncomingAttackFaction",
	"FleetBattle",
	"Victory",
	"Defeat",
	"Event",
	"ArmadaCreated",
	"ArmadaCanceled",
	"ArmadaIncomingAttack",
	"ArmadaBattleWon",
	"ArmadaBattleLost",
	"DiplomacyUpdated",
	"JoinedTakeover",
	"CompetitorJoinedTakeover",
	"AbandonedTerritory",
	"TakeoverVictory",
	"TakeoverDefeat",
	"TreasuryProgress",
	"TreasuryFull",
	"Achievement",
	"AssaultVictory",
	"AssaultDefeat",
	"ChallengeComplete",
	"ChallengeFailed",
	"StrikeHit",
	"StrikeDefeat",
	"WarchestProgress",
	"WarchestFull",
	"PartialVictory",
	"ArenaTimeLeft",
	"ChainedEventScored",
	"FleetPresetApplied",
	"SurgeWarmUpEnded",
	"SurgeHostileGroupDefeated",
	"SurgeTimeLeft",
] as const;

export type BannerType = (typeof BannerTypes)[number];
