import type { ConfigDefinition } from "../structure";

export const graphicsDefinitions: ConfigDefinition[] = [
	{
		group: "Graphics",
		subgroup: "Options",
		key: "borderless_fullscreen",
		label: "Borderless Fullscreen (F11)",
		type: "checkbox",
		description: "Allow borderless full screen mode, set to false to disable",
	},
	{
		group: "Graphics",
		subgroup: "Options",
		key: "allow_cursor",
		label: "Allow changes to the cursor",
		type: "checkbox",
		description: "Allow the system cursor to be replaced? (On by default)",
	},
	{
		group: "Graphics",
		subgroup: "Options",
		key: "use_presets_as_default",
		label: "Use Presets as Default",
		type: "checkbox",
		description: "After using a zoom preset it will be set as default zoom",
	},
	{
		group: "Graphics",
		subgroup: "Options",
		key: "free_resize",
		label: "Free Resize",
		type: "checkbox",
		description: "Allow free resizing, set to false to disable",
	},
	{
		group: "Graphics",
		subgroup: "Options",
		key: "show_all_resolutions",
		label: "Show All Resolutions",
		type: "checkbox",
		description: "To enable additional resolution options set this to true",
	},
	{
		group: "Graphics",
		subgroup: "Loader",
		key: "loader_enabled",
		label: "Enable Loader Screen",
		type: "checkbox",
		description: "Set to true to use the loader_image for the loading screen",
	},
	{
		group: "Graphics",
		subgroup: "Loader",
		key: "loader_transition",
		label: "Enable Transition Screen",
		type: "checkbox",
		description:
			"Set to true to use the loader image for the transition screen",
	},
	{
		group: "Graphics",
		subgroup: "Loader",
		key: "loader_image",
		label: "Loader Image Path",
		type: "textbox",
		description:
			"Path to the custom loading screen image (leave blank for embedded image)",
	},
	{
		group: "Graphics",
		subgroup: "Display",
		key: "ui_scale",
		label: "UI Scale",
		type: "slider",
		min: 0.5,
		max: 2.0,
		step: 0.05,
		description:
			"This specifies the amount to scale the UI by, 1.0 being default",
	},
	{
		group: "Graphics",
		subgroup: "Display",
		key: "ui_scale_adjust",
		label: "UI Scale Adjust",
		type: "slider",
		min: 0,
		max: 0.1,
		step: 0.01,
		description:
			"This specifies the amount to adjust the scale by, 0.05 being default",
	},
	{
		group: "Graphics",
		subgroup: "Display",
		key: "ui_scale_viewer",
		label: "UI Viewer Scale",
		type: "slider",
		min: 0.5,
		max: 2.0,
		step: 0.05,
		description:
			"This specifies the amount to scale the UI Object Viewers by, 1.0 being default",
	},
	{
		group: "Graphics",
		subgroup: "Display",
		key: "transition_time",
		label: "Transition Time",
		type: "slider",
		min: 0,
		max: 1,
		step: 0.001,
		description:
			"Amount of time to spend between transitions, increase to slow transitions down",
	},
	{
		group: "Graphics",
		subgroup: "Zoom",
		key: "default_system_zoom",
		label: "Default System Zoom",
		type: "slider",
		min: 0,
		max: 5000,
		step: 50,
		description:
			"Set to 0.0 to disable custom zoom; enter system at specified zoom otherwise",
	},
	{
		group: "Graphics",
		subgroup: "Keyboard",
		key: "keyboard_zoom_speed",
		label: "Keyboard Zoom Speed",
		type: "slider",
		min: 100,
		max: 1000,
		step: 10,
		description:
			"This controls the zoom speed when using Q/E in System View, defaults to 350",
	},
	{
		group: "Graphics",
		subgroup: "Keyboard",
		key: "system_pan_momentum_falloff",
		label: "System Pan Momentum Falloff",
		type: "slider",
		min: 0,
		max: 1,
		step: 0.01,
		description:
			"Controls how quickly the momentum falls off when letting go of the mouse. Lower = quicker stop. Defaults to 0.8",
	},
	{
		group: "Graphics",
		subgroup: "Keyboard",
		key: "system_pan_momentum",
		label: "System Pan Momentum",
		type: "slider",
		min: 0,
		max: 1,
		step: 0.01,
		description: "Controls the system pan momentum speed. Defaults to 0.4",
	},
	// Zoom presets F1-F5
	...[1, 2, 3, 4, 5].map((n) => ({
		group: "Graphics",
		subgroup: "Zoom",
		key: `system_zoom_preset_${n}`,
		label: `F${n} Zoom Preset`,
		type: "slider" as const,
		min: 10,
		max: 10000,
		step: 10,
		description: `Zoom preset F${n} for system view`,
	})),
	{
		group: "Graphics",
		key: "zoom",
		subgroup: "Zoom",
		label: "Maximum Zoom",
		type: "slider",
		min: 1000,
		max: 10000,
		step: 100,
		description:
			"This controls the maximum zoom distance in System View. Default is 2500. Higher values increase label distance",
	},
];
