import type { ConfigDefinition } from "../structure";

export const patchesDefinitions: ConfigDefinition[] = [
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "bufffixhooks",
		label: "Buff Fix Hooks",
		description: "Enable the buff fixes",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "chatpatches",
		label: "Chat Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "freeresizehooks",
		label: "Free Resize Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "hotkeyhooks",
		label: "Hotkey Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "improveresponsivenesshooks",
		label: "Improve Responsiveness Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "miscpatches",
		label: "Misc Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "objecttracker",
		label: "Object Tracker",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "panhooks",
		label: "Pan Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "resolutionlistfix",
		label: "Resolution List Fix",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "syncpatches",
		label: "Sync Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "tempcrashfixes",
		label: "Temporary Crash Fixes",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "testpatches",
		label: "Test Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "toastbannerhooks",
		label: "Toast Banner Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "uiscalehooks",
		label: "UI Scale Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "zoomhooks",
		label: "Zoom Hooks",
		type: "checkbox",
	},
];
