import type { ConfigDefinition } from "../structure";

export const patchesDefinitions: ConfigDefinition[] = [
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "bufffixhooks",
		label: "Buff Fix Hooks",
		description: "Enable the buff fixes",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "chatpatches",
		label: "Chat Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "freeresizehooks",
		label: "Free Resize Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "game_version",
		label: "Game Version",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "hotkeyhooks",
		label: "Hotkey Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "loadingscreenhooks",
		label: "Loading Screen Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "transitionscreenhooks",
		label: "Transition Screen Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "miscpatches",
		label: "Misc Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "objecttracker",
		label: "Object Tracker",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "panhooks",
		label: "Pan Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "syncpatches",
		label: "Sync Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "tempcrashfixes",
		label: "Temporary Crash Fixes",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "testpatches",
		label: "Test Patches",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "toastbannerhooks",
		label: "Toast Banner Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "uiscalehooks",
		label: "UI Scale Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "zoomhooks",
		label: "Zoom Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "giftsbulkclaimhooks",
		label: "Gifts Bulk Claim Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "focussearch",
		label: "Focus Search",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "cargoformathooks",
		label: "Cargo Format Hooks",
		type: "checkbox",
	},
	{
		group: "Patches",
		subgroup: "Leave Well Alone",
		key: "officersorthooks",
		label: "Officer Sort Hooks",
		type: "checkbox",
	},
];
