import type { ConfigDefinition } from "../structure";

const experimental_feature = "[EXPERIMENTAL] ";

export const shortcutDefinitions: ConfigDefinition[] = [
	// Queue & Primary
	{
		group: "Shortcuts",
		subgroup: "Queue & Primary",
		key: "toggle_queue",
		label: "Toggle Kir'Shara queue",
		type: "textbox",
		description: "Requires Kir'Shara artifact",
	},
	{
		group: "Shortcuts",
		subgroup: "Queue & Primary",
		key: "action_queue",
		label: "Queue hostiles instead of attacking",
		type: "textbox",
		description: "Requires Kir'Shara",
	},
	{
		group: "Shortcuts",
		subgroup: "Queue & Primary",
		key: "action_queue_clear",
		label: "Clear hostile queue",
		type: "textbox",
		description: "Does not cancel primary attack",
	},
	{
		group: "Shortcuts",
		subgroup: "Queue & Primary",
		key: "action_primary",
		label: "Primary action",
		type: "textbox",
		description: "SPACE or Mouse1",
	},
	{
		group: "Shortcuts",
		subgroup: "Queue & Primary",
		key: "action_secondary",
		label: "Secondary action",
		type: "textbox",
		description: "TAB or Mouse4",
	},
	{
		group: "Shortcuts",
		subgroup: "Queue & Primary",
		key: "action_view",
		label: "Toggle rewards view",
		type: "textbox",
		description: "V or Mouse2",
	},

	// Hotkeys Master Switch & Logs
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "set_hotkeys_disabled",
		label: "Disable all hotkeys",
		type: "textbox",
		description: "CTRL-ALT-MINUS",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "set_hotkeys_enabled",
		label: "Enable all hotkeys",
		type: "textbox",
		description: "CTRL-ALT-=",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "log_off",
		label: "Log Nothing",
		type: "textbox",
		description: "CTRL-SHIFT-F12",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "log_error",
		label: "Log error",
		type: "textbox",
		description: "CTRL-SHIFT-F11",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "log_warn",
		label: "Log warn",
		type: "textbox",
		description: "CTRL-SHIFT-F10",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "log_debug",
		label: "Log debug",
		type: "textbox",
		description: "CTRL-SHIFT-F9",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "log_info",
		label: "Log info",
		type: "textbox",
		description: "CTRL-SHIFT-F8",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "log_trace",
		label: "Log trace",
		type: "textbox",
		description: "CTRL-SHIFT-F7",
	},
	{
		group: "Shortcuts",
		subgroup: "Hotkeys Master Switch & Logs",
		key: "quit",
		label: "Fast exit game",
		type: "textbox",
		description: "F10",
	},

	// Recall & Repair
	{
		group: "Shortcuts",
		subgroup: "Recall & Repair",
		key: "action_recall",
		label: "Recall ship",
		type: "textbox",
		description: "R or Mouse3",
	},
	{
		group: "Shortcuts",
		subgroup: "Recall & Repair",
		key: "action_recall_cancel",
		label: "Cancel a recall",
		type: "textbox",
		description: "SPACE or Mouse1",
	},
	{
		group: "Shortcuts",
		subgroup: "Recall & Repair",
		key: "action_repair",
		label: "Repair ship",
		type: "textbox",
		description: "R or Mouse3",
	},

	// Chat Tabs & Selection
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_chatglobal",
		label: "Select Global chat tab",
		type: "textbox",
		description: "CTRL-1",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_chatalliance",
		label: "Select Alliance chat tab",
		type: "textbox",
		description: "CTRL-2",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_chatprivate",
		label: "Select Private chat tab",
		type: "textbox",
		description: "CTRL-3",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_current",
		label: "Locate current ship",
		type: "textbox",
		description: "CTRL-SPACE",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship1",
		label: "Select ship 1",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship2",
		label: "Select ship 2",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship3",
		label: "Select ship 3",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship4",
		label: "Select ship 4",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship5",
		label: "Select ship 5",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship6",
		label: "Select ship 6",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship7",
		label: "Select ship 7",
		type: "textbox",
		description: "See select_timer",
	},
	{
		group: "Shortcuts",
		subgroup: "Chat Tabs & Selection",
		key: "select_ship8",
		label: "Select ship 8",
		type: "textbox",
		description: "See select_timer",
	},

	// Zoom & Presets
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_in",
		label: "Zoom in",
		type: "textbox",
		description: "Q",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_out",
		label: "Zoom out",
		type: "textbox",
		description: "E",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_min",
		label: "Zoom min",
		type: "textbox",
		description: "BACKSPACE",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_max",
		label: "Zoom max",
		type: "textbox",
		description: "MINUS",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_reset",
		label: "Reset zoom",
		type: "textbox",
		description: "=",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_preset1",
		label: "Zoom preset F1",
		type: "textbox",
		description: "F1",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_preset2",
		label: "Zoom preset F2",
		type: "textbox",
		description: "F2",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_preset3",
		label: "Zoom preset F3",
		type: "textbox",
		description: "F3",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_preset4",
		label: "Zoom preset F4",
		type: "textbox",
		description: "F4",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "zoom_preset5",
		label: "Zoom preset F5",
		type: "textbox",
		description: "F5",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "set_zoom_default",
		label: "Set default zoom",
		type: "textbox",
		description: "CTRL-=",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "set_zoom_preset1",
		label: "Set zoom preset F1",
		type: "textbox",
		description: "SHIFT-F1",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "set_zoom_preset2",
		label: "Set zoom preset F2",
		type: "textbox",
		description: "SHIFT-F2",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "set_zoom_preset3",
		label: "Set zoom preset F3",
		type: "textbox",
		description: "SHIFT-F3",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "set_zoom_preset4",
		label: "Set zoom preset F4",
		type: "textbox",
		description: "SHIFT-F4",
	},
	{
		group: "Shortcuts",
		subgroup: "Zoom & Presets",
		key: "set_zoom_preset5",
		label: "Set zoom preset F5",
		type: "textbox",
		description: "SHIFT-F5",
	},

	// UI Scale
	{
		group: "Shortcuts",
		subgroup: "UI Scale",
		key: "ui_scaleup",
		label: "UI Scale Up",
		type: "textbox",
		description: "PGUP",
	},
	{
		group: "Shortcuts",
		subgroup: "UI Scale",
		key: "ui_scaledown",
		label: "UI Scale Down",
		type: "textbox",
		description: "PGDOWN",
	},
	{
		group: "Shortcuts",
		subgroup: "UI Scale",
		key: "ui_scaleviewerup",
		label: "UI Viewer Scale Up",
		type: "textbox",
		description: "SHIFT-PGUP",
	},
	{
		group: "Shortcuts",
		subgroup: "UI Scale",
		key: "ui_scaleviewerdown",
		label: "UI Viewer Scale Down",
		type: "textbox",
		description: "SHIFT-PGDOWN",
	},

	// Screens
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_alliance",
		label: "Show Alliance",
		type: "textbox",
		description: "Show Alliance",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_alliance_armada",
		label: "Show Alliance Armada",
		type: "textbox",
		description: "Show Alliance Armada",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_alliance_help",
		label: "Show Alliance Help",
		type: "textbox",
		description: "Show Alliance Help",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_artifacts",
		label: "Show Artifacts",
		type: "textbox",
		description: "Show Artifacts",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_awayteam",
		label: "Show Away Team",
		type: "textbox",
		description: "Show Away Team",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_bookmarks",
		label: "Show Bookmarks",
		type: "textbox",
		description: "Show Bookmarks",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_chat",
		label: "Show Chat Full Screen",
		type: "textbox",
		description: "Show Chat Full Screen",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_chatside1",
		label: "Show Chat Left",
		type: "textbox",
		description: "Show Chat Left",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_chatside2",
		label: "Show Chat Right",
		type: "textbox",
		description: "Show Chat Right",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_commander",
		label: "Go to Fleet Commander",
		type: "textbox",
		description: "Go to Fleet Commander",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_daily",
		label: "Go to Daily Missions",
		type: "textbox",
		description: "Go to Daily Missions",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_events",
		label: "Go to Events",
		type: "textbox",
		description: "Go to Events",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_exocomp",
		label: "Go to Exocomp",
		type: "textbox",
		description: "Go to Exocomp",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_factions",
		label: "Go to Factions",
		type: "textbox",
		description: "Go to Factions",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_galaxy",
		label: "Go to Galaxy",
		type: "textbox",
		description: "Go to Galaxy",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_gifts",
		label: "Go to Gifts",
		type: "textbox",
		description: "Go to Gifts",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_inventory",
		label: "Go to Inventory",
		type: "textbox",
		description: "Go to Inventory",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_missions",
		label: "Go to Missions",
		type: "textbox",
		description: "Go to Missions",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_officers",
		label: "Go to Officers",
		type: "textbox",
		description: "Go to Officers",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_qtrials",
		label: "Go to Q Trials",
		type: "textbox",
		description: "Go to Q Trials",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_refinery",
		label: "Go to Refinery",
		type: "textbox",
		description: "Go to Refinery",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_research",
		label: "Go to Research",
		type: "textbox",
		description: "Go to Research",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_scrapyard",
		label: "Go to Scrap Yard",
		type: "textbox",
		description: "Go to Scrap Yard",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_settings",
		label: "Go to Settings",
		type: "textbox",
		description: "Go to Settings",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_ships",
		label: "Go to Manage Ships",
		type: "textbox",
		description: "Go to Manage Ships",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_stationexterior",
		label: "Station Exterior",
		type: "textbox",
		description: "Station Exterior",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_stationinterior",
		label: "Station Interior",
		type: "textbox",
		description: "Station Interior",
	},
	{
		group: "Shortcuts",
		subgroup: "Screens",
		key: "show_system",
		label: "Go to System",
		type: "textbox",
		description: "Go to System",
	},
	{
		group: "Shortcuts",
		subgroup: "Experimental",
		key: "show_lookup",
		label: "Show bookmark lookup screen",
		type: "textbox",
		description: `${experimental_feature}Shows the bookmark->lookup screen`,
	},
	{
		group: "Shortcuts",
		subgroup: "Experimental",
		key: "move_up",
		label: "Move up",
		type: "textbox",
		description: `${experimental_feature}Moves up the screen`,
	},
	{
		group: "Shortcuts",
		subgroup: "Experimental",
		key: "move_down",
		label: "Move down",
		type: "textbox",
		description: `${experimental_feature}Moves down the screen`,
	},
	{
		group: "Shortcuts",
		subgroup: "Experimental",
		key: "move_left",
		label: "Move left",
		type: "textbox",
		description: `${experimental_feature}Moves left the screen`,
	},
	{
		group: "Shortcuts",
		subgroup: "Experimental",
		key: "move_right",
		label: "Move right",
		type: "textbox",
		description: `${experimental_feature}Moves right the screen`,
	},

	// Cargo & Locate
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_cargo_default",
		label: "Toggle Default cargo preview",
		type: "textbox",
		description: "Whether to show cargo by default",
	},
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_cargo_player",
		label: "Toggle Player cargo preview",
		type: "textbox",
		description: "Whether to show Player cargo by default",
	},
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_cargo_station",
		label: "Toggle Station cargo preview",
		type: "textbox",
		description: "Whether to show Station cargo by default",
	},
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_cargo_hostile",
		label: "Toggle Hostile cargo preview",
		type: "textbox",
		description: "Whether to show Hostile cargo by default",
	},
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_cargo_armada",
		label: "Toggle Armada cargo preview",
		type: "textbox",
		description: "Whether to show armada cargo by default",
	},
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_preview_locate",
		label: "Toggle preview locate",
		type: "textbox",
		description: "Whether to allow locate when previews are displayed",
	},
	{
		group: "Shortcuts",
		subgroup: "Cargo & Locate",
		key: "toggle_preview_recall",
		label: "Toggle preview recall",
		type: "textbox",
		description: "Whether to allow recall when previews are displayed",
	},
];
