import type { ConfigDefinition } from "../structure";

export const syncDefinitions: ConfigDefinition[] = [
	{
		group: "Sync",
		subgroup: "Host",
		key: "token",
		label: "Token",
		type: "textbox",
		description: "The token that is used to provide authentication",
	},
	{
		group: "Sync",
		subgroup: "Host",
		key: "url",
		label: "Target Url",
		type: "textbox",
		description: "The url of the server to send data to",
	},
	{
		group: "Sync",
		subgroup: "Host",
		key: "proxy",
		label: "Proxy Url",
		type: "textbox",
		description: "The url of the server to proxy the connection through",
	},
	{
		group: "Sync",
		subgroup: "Diagnostics",
		key: "logging",
		label: "Enable Logging",
		type: "checkbox",
		description: "Do you want to enable sync logging?",
	},
	{
		group: "Sync",
		subgroup: "Diagnostics",
		key: "debug",
		label: "Enable Debug",
		type: "checkbox",
		description: "Do you want to enable sync debug? (Requires sync logging)",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "battlelogs",
		label: "Battlelogs",
		type: "checkbox",
		description: "Do you want to sync battlelogs?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "buildings",
		label: "Buildings",
		type: "checkbox",
		description: "Do you want to sync building data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "missions",
		label: "Missions",
		type: "checkbox",
		description: "Do you want to sync mission data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "officer",
		label: "Officers",
		type: "checkbox",
		description: "Do you want to sync owned officer data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "research",
		label: "Researchs",
		type: "checkbox",
		description: "Do you want to sync research data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "resources",
		label: "Resources",
		type: "checkbox",
		description: "Do you want to sync resource data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "ships",
		label: "Ships",
		type: "checkbox",
		description: "Do you want to sync owned ship data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "tech",
		label: "Techs",
		type: "checkbox",
		description: "Do you want to sync owned forbidden tech data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "traits",
		label: "Traits",
		type: "checkbox",
		description: "Do you want to sync trait data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "buffs",
		label: "Buffs",
		type: "checkbox",
		description: "Do you want to sync buff data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "inventory",
		label: "Inventory",
		type: "checkbox",
		description: "Do you want to sync inventory data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "jobs",
		label: "Jobs",
		type: "checkbox",
		description: "Do you want to sync jobs data?",
	},
	{
		group: "Sync",
		subgroup: "Data",
		key: "slots",
		label: "Slots",
		type: "checkbox",
		description: "Do you want to sync slots data?",
	},
	{
		group: "Sync",
		subgroup: "Network",
		key: "resolver_cache_ttl",
		label: "Resolver Cache",
		type: "textbox",
		description: "How long to keep cached items (ms)",
	},
	{
		group: "Sync",
		subgroup: "Network",
		key: "verify_ssl",
		label: "Verify SSL",
		type: "checkbox",
		description: "Should SSL Certificates be checked?",
	},
];
