import type { SyncTargetConfiguration, TomlConfig } from "./types";

// default SyncTarget
export const defaultSyncTarget: SyncTargetConfiguration = {
	battlelogs: true,
	buffs: true,
	buildings: true,
	inventory: true,
	jobs: true,
	missions: true,
	officer: true,
	proxy: "",
	research: true,
	resources: true,
	ships: true,
	slots: true,
	tech: true,
	traits: true,
	token: "",
	url: "",
};

// defaultConfig (fill all defaults here)
export const defaultConfig: TomlConfig = {
	buffs: {
		use_out_of_dock_power: true,
	},
	config: {
		assets_url_override: "",
		settings_url: "",
	},
	control: {
		enable_experimental: false,
		hotkeys_enabled: true,
		hotkeys_extended: true,
		use_scopely_hotkeys: false,
		queue_enabled: true,
		select_timer: 500,
	},
	graphics: {
		borderless_fullscreen: true,
		allow_cursor: true,
		default_system_zoom: 1750,
		free_resize: true,
		keyboard_zoom_speed: 350,
		loader_enabled: true,
		loader_transition: true,
		loader_image: "",
		show_all_resolutions: false,
		system_pan_momentum_falloff: 0.8,
		system_pan_momentum: 0.4,
		system_zoom_preset_1: 50,
		system_zoom_preset_2: 500,
		system_zoom_preset_3: 1250,
		system_zoom_preset_4: 2750,
		system_zoom_preset_5: 5000,
		transition_time: 0.01,
		ui_scale: 0.6,
		ui_scale_adjust: 0.05,
		ui_scale_viewer: 1.2,
		use_presets_as_default: true,
		zoom: 5000,
	},
	patches: {
		bufffixhooks: true,
		chatpatches: true,
		freeresizehooks: true,
		hotkeyhooks: true,
		improveresponsivenesshooks: true,
		miscpatches: true,
		objecttracker: true,
		panhooks: true,
		resolutionlistfix: true,
		syncpatches: true,
		tempcrashfixes: true,
		testpatches: true,
		toastbannerhooks: true,
		uiscalehooks: true,
		zoomhooks: true,
	},
	shortcuts: {
		toggle_queue: "CTRL-Q",
		action_queue: "SPACE|MOUSE1",
		action_queue_clear: "CTRL-C",
		action_primary: "SPACE|MOUSE1",
		action_recall: "R|MOUSE3",
		action_recall_cancel: "SPACE|MOUSE1",
		action_repair: "R|MOUSE3",
		action_secondary: "TAB|MOUSE4",
		action_view: "V|MOUSE2",
		set_hotkeys_disabled: "CTRL-ALT-MINUS",
		set_hotkeys_enabled: "CTRL-ALT-=",
		log_off: "CTRL-SHIFT-F12",
		log_error: "CTRL-SHIFT-F11",
		log_warn: "CTRL-SHIFT-F10",
		log_debug: "CTRL-SHIFT-F9",
		log_info: "CTRL-SHIFT-F8",
		log_trace: "CTRL-SHIFT-F7",
		quit: "F10",
		select_chatalliance: "CTRL-2",
		select_chatglobal: "CTRL-1",
		select_chatprivate: "CTRL-3",
		select_current: "CTRL-SPACE",
		select_ship1: "1",
		select_ship2: "2",
		select_ship3: "3",
		select_ship4: "4",
		select_ship5: "5",
		select_ship6: "6",
		select_ship7: "7",
		select_ship8: "8",
		set_zoom_default: "CTRL-=",
		set_zoom_preset1: "SHIFT-F1",
		set_zoom_preset2: "SHIFT-F2",
		set_zoom_preset3: "SHIFT-F3",
		set_zoom_preset4: "SHIFT-F4",
		set_zoom_preset5: "SHIFT-F5",
		show_alliance: "ALT-'",
		show_alliance_armada: "CTRL-'",
		show_alliance_help: "SHIFT-'",
		show_artifacts: "SHIFT-I",
		show_awayteam: "T",
		show_bookmarks: "B",
		show_chat: "C",
		show_chatside1: "ALT-C",
		show_chatside2: "`",
		show_commander: "O",
		show_daily: "Z",
		show_events: "SHIFT-E",
		show_exocomp: "X",
		show_factions: "F",
		show_galaxy: "G",
		show_gifts: "/",
		show_inventory: "I",
		show_lookup: "L",
		show_missions: "M",
		show_officers: "SHIFT-O",
		show_qtrials: "SHIFT-Q",
		show_refinery: "SHIFT-F",
		show_research: "U",
		show_scrapyard: "Y",
		show_settings: "SHIFT-S",
		show_ships: "N",
		show_stationexterior: "SHIFT-G",
		show_stationinterior: "SHIFT-H",
		show_system: "H",
		toggle_cargo_armada: "ALT-5",
		toggle_cargo_default: "ALT-1",
		toggle_cargo_hostile: "ALT-4",
		toggle_cargo_player: "ALT-2",
		toggle_cargo_station: "ALT-3",
		toggle_preview_locate: "CTRL-R",
		toggle_preview_recall: "CTRL-T",
		ui_scaledown: "PGDOWN",
		ui_scaleup: "PGUP",
		ui_scaleviewerdown: "SHIFT-PGDOWN",
		ui_scaleviewerup: "SHIFT-PGUP",
		zoom_in: "Q",
		zoom_max: "MINUS",
		zoom_min: "BACKSPACE",
		zoom_out: "E",
		zoom_reset: "=",
		zoom_preset1: "F1",
		zoom_preset2: "F2",
		zoom_preset3: "F3",
		zoom_preset4: "F4",
		zoom_preset5: "F5",
		move_up: "W",
		move_down: "S",
		move_left: "A",
		move_right: "D",
	},

	// Sync
	// Sync section using defaultSyncTarget
	sync: {
		...defaultSyncTarget, // spreads battlelogs, buffs, buildings, inventory, jobs, missions, officer, research, resources, ships, slots, tech, traits, proxy, token, url
		debug: false,
		logging: false,
		verify_ssl: true,
		resolver_cache_ttl: 300,
		targets: {
			spocksclub: { ...defaultSyncTarget },
			nextspocksclub: { ...defaultSyncTarget },
		},
	},
	ui: {
		always_skip_reveal_sequence: true,
		auto_confirm_discovery: true,
		disable_escape_exit: true,
		disable_first_popup: false,
		disable_galaxy_chat: false,
		disable_move_keys: false,
		disable_preview_locate: false,
		disable_preview_recall: false,
		disable_toast_banners: false,
		disable_veil_chat: false,
		disabled_banner_types: "",
		extend_donation_max: 80,
		extend_donation_slider: true,
		show_armada_cargo: true,
		show_cargo_default: true,
		show_hostile_cargo: true,
		show_player_cargo: true,
		show_station_cargo: true,
	},
};
