import { allDefinitions } from "./definitions";
import { generateLines } from "./letters";
import type { ConfigDefinition } from "./structure";
import { groupDisplayNames } from "./structure";
import type { SyncConfiguration, TomlConfig } from "./types";

/**
 * Generate TOML string from a partial config.
 */
export function generateToml(
	config: Partial<TomlConfig>,
	includeMainHeader: boolean = true,
	includeSectionHeader: boolean = true,
	includeSubgroupHeader: boolean = true,
	includeItemHeader: boolean = true,
): string {
	let tomlStr = "";

	if (includeMainHeader) {
		tomlStr +=
			writeHeader("STFC:Mod", false) +
			`#   Generated on ${new Date().toISOString()}`;
		const headerLetter = randomLetter();
		const headerNumber = randomNumber();

		tomlStr += `${[
			``,
			``,
			`This configuration file was generated by https://modconfig.pages.dev`,
			`and is provided as-is.  If there are any issues with the STFC Community Mod`,
			`the configuration or the configuration website tool, please consider reporting`,
			`these to:`,
			``,
			`    Discord : https://discord.gg/PrpHgs7Vjs`,
			`    GitHub  : https://github.com/netniV/stfc-mod`,
			``,
			`Today's configuration file is brought to you by the letter ${headerLetter} and the number ${headerNumber}`,
			``,
		].join("\n#   ")}\n\n`;
	}

	// --- Write all non-sync sections first
	for (const [sectionName, sectionValue] of Object.entries(config) as [
		string,
		unknown,
	][]) {
		if (sectionName.toLowerCase() === "sync") continue;
		tomlStr += writeSectionFromConfig(
			sectionName,
			sectionValue as Record<string, unknown>,
			undefined,
			undefined,
			includeSectionHeader,
			includeSubgroupHeader,
			includeItemHeader,
		);
	}

	// --- Write [sync] and [sync.targets.*] last
	const syncSection = config.sync;
	if (syncSection) {
		tomlStr += writeSyncSections(
			syncSection,
			includeSectionHeader,
			includeSubgroupHeader,
			includeItemHeader,
		);
	}

	return tomlStr;
}

/**
 * Handles [sync] and [sync.targets.*] sections
 */
function writeSyncSections(
	syncSection: SyncConfiguration,
	includeCommentSection: boolean,
	includeCommentSubgroup: boolean,
	includeCommentItem: boolean,
): string {
	if (!syncSection || typeof syncSection !== "object") return "";

	let str = "";

	// --- Write [sync] (excluding targets)
	const syncMain = { ...syncSection };
	delete syncMain.targets;
	str += writeSectionFromConfig("sync", syncMain, undefined);

	// --- Write [sync.targets.*] alphabetically
	if (syncSection.targets && typeof syncSection.targets === "object") {
		const sortedTargets = Object.keys(syncSection.targets).sort((a, b) =>
			a.localeCompare(b),
		);

		for (const targetName of sortedTargets) {
			const targetConfig = syncSection.targets[targetName];
			const defaultTarget = syncSection ?? {};
			str += writeSectionFromConfig(
				`sync.targets.${targetName}`,
				targetConfig,
				`Sync ${targetName}`,
				defaultTarget,
				includeCommentSection,
				includeCommentSubgroup,
				includeCommentItem,
			);
		}
	}

	return str;
}

function writeHeader(header: string, box: boolean = true): string {
	const headerLines = generateLines(header, !box);

	let headerPadLeft = " <[";
	let headerPadRight = "]> ";
	let headerSpacing = "   ";
	let headerPadSpace = "   ";
	let headerRepeater1 = "=";

	if (!box) {
		headerPadLeft = " +-";
		headerPadRight = "-+ ";
		headerPadSpace = " | ";
		headerSpacing = "   ";
		headerRepeater1 = "-";
	}

	// Precompute repeated elements
	const lineLength = headerLines[0].length;
	const outerLine = `# ${headerPadLeft}${headerRepeater1.repeat(
		lineLength + headerPadLeft.length + headerPadRight.length,
	)}${headerPadRight}`;
	const spacerLine = `# ${headerPadSpace}${headerSpacing}${" ".repeat(
		lineLength,
	)}${headerSpacing}${headerPadSpace}`;

	const str = [
		outerLine,
		//    fillerLine,
		spacerLine,
		...headerLines.map(
			(line) =>
				`# ${headerPadSpace}${headerSpacing}${line}${headerSpacing}${headerPadSpace}`,
		),
		spacerLine,
		//    fillerLine,
		outerLine,
		``,
	].join("\n");
	return str;
}

function toTitleCase(str: string) {
	return str
		.toLowerCase()
		.split(" ")
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(" ");
}

// Generate random letter (A-Z)
function randomLetter() {
	const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	const index = Math.floor(Math.random() * letters.length);
	return letters[index];
}

// Generate random number (0-9)
function randomNumber() {
	return Math.floor(Math.random() * 10);
}

/**
 * Generic TOML section writer with subgroup support and friendly section names.
 */
function writeSectionFromConfig(
	sectionName: string,
	sectionValue: Record<string, unknown>,
	sectionHeader?: string,
	defaults?: Record<string, unknown>,
	includeCommentSection?: boolean,
	includeCommentSubgroup?: boolean,
	includeCommentItem?: boolean,
): string {
	const sectionKey = toTitleCase(sectionName);
	const displayName =
		sectionHeader ?? groupDisplayNames[sectionKey] ?? sectionKey;

	let str = "";
	if (includeCommentSection ?? true) str += writeHeader(displayName);
	str += `\n[${sectionName.toLowerCase()}]\n`;

	if (typeof sectionValue !== "object" || sectionValue === null) {
		return `${str}\n`;
	}

	const items: {
		key: string;
		value: unknown;
		type?: string;
		comment: string;
		subgroup?: string;
	}[] = [];

	for (const [key, value] of Object.entries(sectionValue)) {
		const def = findDefinition(sectionName.toLowerCase(), key);
		const type = def?.type ?? inferType(value);
		const finalValue =
			value ?? getDefaultForType(type as ConfigDefinition["type"]);
		const comment = def?.description ?? "";
		const subgroup = def?.subgroup;

		// Skip writing if value matches default
		const defaultValue = defaults?.[key];
		if (defaultValue !== undefined && defaultValue === finalValue) continue;

		items.push({ key, value: finalValue, type, comment, subgroup });
	}

	const ungrouped = items
		.filter((i) => !i.subgroup)
		.sort((a, b) => a.key.localeCompare(b.key));
	const grouped = items
		.filter((i) => i.subgroup)
		.sort((a, b) => {
			const aSubgroup = a.subgroup ?? "";
			const bSubgroup = b.subgroup ?? "";
			if (aSubgroup === bSubgroup) return a.key.localeCompare(b.key);
			return aSubgroup.localeCompare(bSubgroup);
		});

	// --- Write ungrouped items first
	let first = true;
	for (const item of ungrouped) {
		if (item.comment && includeCommentItem) {
			if (!first) str += "\n";
			str += `# ${item.comment}\n`;
		}
		str += `${item.key.toLowerCase()} = ${formatTomlValue(
			item.value,
			item.type,
		)}\n`;
		first = false;
	}

	// --- Then grouped items, with subgroup comment once per subgroup
	let currentSubgroup: string | undefined;
	for (const item of grouped) {
		if (item.subgroup !== currentSubgroup) {
			first = true;
			const titleSubgroup = item.subgroup
				?.split(".")
				.map((w) => w[0].toUpperCase() + w.slice(1))
				.join(" ");

			const subgroupHeader = `Subgroup: ${titleSubgroup}`;
			const dashes = "-".repeat(subgroupHeader.length);

			if (includeCommentSubgroup) {
				str += `\n# ${subgroupHeader}\n# ${dashes}\n\n`;
			}
			currentSubgroup = item.subgroup;
		}

		if (item.comment && includeCommentItem) {
			if (!first) str += `\n`;
			str += `# ${item.comment}\n`;
		}

		str += `${item.key.toLowerCase()} = ${formatTomlValue(
			item.value,
			item.type,
		)}\n`;
		first = false;
	}

	str += `\n`;
	return str;
}

/**
 * Definition resolver for normal and sync-target sections
 */
function findDefinition(
	section: string,
	key: string,
): ConfigDefinition | undefined {
	return allDefinitions.find((d) => {
		const defGroup = d.group?.toLowerCase() ?? "";
		const defKey = String(d.key).toLowerCase();

		if (defGroup === section && defKey === key.toLowerCase()) return true;

		if (section.startsWith("sync.targets.")) {
			return defGroup.startsWith("sync.target") && defKey === key.toLowerCase();
		}

		return false;
	});
}

/**
 * Formats TOML values according to type.
 * Sliders always show at least 1 decimal; other numbers 0 dp.
 */
function formatTomlValue(value: unknown, type: string | undefined): string {
	switch (type) {
		case "textbox":
			return `"${String(value ?? "")
				.replace(/\\/g, "\\\\")
				.replace(/"/g, '\\"')}"`;
		case "checkbox":
			return Boolean(value).toString();
		case "number": {
			const num = Number(value ?? 0);
			return Math.round(num).toString();
		}
		case "slider": {
			const num = Number(value ?? 0);
			return num % 1 === 0 ? num.toFixed(1) : num.toString();
		}
		default: {
			if (typeof value === "string") return `"${value.replace(/"/g, '\\"')}"`;
			if (typeof value === "boolean") return value ? "true" : "false";
			if (typeof value === "number") return Math.round(value).toString();
			return `"${String(value ?? "")}"`;
		}
	}
}

/**
 * Default values per type
 */
function getDefaultForType(type: ConfigDefinition["type"]) {
	switch (type) {
		case "checkbox":
			return false;
		case "slider":
			return 0.0;
		case "number":
			return 0;
		case "textbox":
			return "";
		default:
			return null;
	}
}

/**
 * Type inference fallback
 */
function inferType(value: unknown): ConfigDefinition["type"] {
	if (typeof value === "boolean") return "checkbox";
	if (typeof value === "number") return "number";
	if (typeof value === "string") return "textbox";
	return "textbox";
}
