name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@da79ef32b786875c075fd0abcfdd173640b96499

      - name: Run Biome
        run: biome ci .
