name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@f08bfa3b989433344d4abe1047904d6b38981b70

      - name: Run Biome
        run: biome ci .
