name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@da27d18dce2352c716f25fed9c16cde28af1c47e

      - name: Run Biome
        run: biome ci .
